### ISSUE TITLE
Review bot as GH Action

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#1244]
As action env:
``` yml
env:
  PR: ${{ github.event.pull_request.html_url }}
  PR_ACTOR: ${{ github.actor }}
```

As action vars:
``` yml
with:
  org: taskany-inc
  team: reviewers
  count: 2
```

As action source:
``` bash
node -pe 'JSON.parse(process.argv[1]).map(u => u.login).filter(l => l !== process.env.PR_ACTOR).join()' "$(gh api \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /orgs/taskany-inc/teams/core/members)"
```

Action!:
- `gh pr edit $PR --add-reviewer monalisa,hubot`

Docs:
- https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
- https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28
- https://cli.github.com/manual/gh_pr_edit

PS: it's possible to do it in workflow yml, but is we have ambitions to share it on marketplace [here](https://github.com/taskany-inc/pr-review-action) I prepared template.
