### ISSUE TITLE
Loading state for Button

### ISSUE THREAD

**Issue by awinogradov** [taskany-inc/issues#171]
So! We need it.

The idea:
Use border animation like here https://codepen.io/mike-schultz/pen/NgQvGO
The first case of usage in validation of project key on create project form. In time of validation we have two variants: valid or not. Validation is async. We can use primary and danger colors for gradient animation in border of Button. Like Jackpot ;)

Relates #168

**Comment by awinogradov** [comment]
``` html
<div class="gradient-border">Loading...</div>
```

``` css
.gradient-border {
  --borderWidth: 1px;
  border-radius: 6px;
  background: #121A17;
  position: relative;
  width: 100px;
  height: 28px;
  color: #16AF71;
  font-family: Helvetica;
  font-weight: 500;
  font-size: 16px;
}
.gradient-border:after {
  content: '';
  position: absolute;
  top: calc(-1 * var(--borderWidth));
  left: calc(-1 * var(--borderWidth));
  height: calc(100% + var(--borderWidth) * 2);
  width: calc(100% + var(--borderWidth) * 2);
  background: linear-gradient(60deg, #16AF71, #1F1F1F, #121212, #16AF71);
  border-radius: calc(2 * 4px);
  z-index: -1;
  animation: animatedgradient 3s ease alternate infinite;
  background-size: 300% 300%;
}

@keyframes animatedgradient {
	0% {
		background-position: 0% 50%;
	}
	50% {
		background-position: 100% 50%;
	}
	100% {
		background-position: 0% 50%;
	}
}
```
